name: on_space
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  chopper: ^7.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  http: ^1.1.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  mockito: ^5.4.3


dev_dependencies:
  bloc_test: ^9.1.4

  build_runner: ^2.4.7
  chopper_generator: ^7.0.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.24.9
  very_good_analysis: ^5.1.0
  
  

flutter:
  uses-material-design: true
  generate: true
  assets:
    - "assets/ca/"
